services:
  moodle-db:
    image: mariadb:10.11
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql

  moodle:
    build:
      context: .
      dockerfile: moodle.Dockerfile
      target: moodle-prod # Safe production image with security settings applied by default
    restart: unless-stopped
    volumes:
      # Moodle source code tracked by Git
      - ./html:/var/www/html
      # Persistent files (user uploads, course files, etc.)
      - ./moodledata:/var/www/moodledata
    depends_on:
      - moodle-db

  moodle-cron:
    build:
      context: .
      dockerfile: moodle.Dockerfile
      target: moodle-prod
    container_name: moodle-cron
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./moodledata:/var/www/moodledata
    depends_on:
      - moodle-db
    # Instead of running the Apache web server, this container runs the Moodle cron every minute in an infinite loop
    command: >
      sh -c "while true; do php /var/www/html/admin/cli/cron.php; sleep 60; done"