services:
  moodle-db:
    image: mariadb:10.11
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./bind-mounts/mariadb_data:/var/lib/mysql

  moodle:
    image: moodlehq/moodle-php-apache:8.3
    restart: unless-stopped
    environment:
      # Fixes zend.exception_ignore_args warning, removes sensitive information from logs in prod
      - PHP_INI-zend.exception_ignore_args=On
    volumes:
      # Moodle source code tracked by Git
      - ./bind-mounts/html:/var/www/html
      # Persistent files (user uploads, course files, etc.)
      - ./bind-mounts/moodledata:/var/www/moodledata
      # Mount our custom initialization scripts
      - ./entrypoint-scripts:/docker-entrypoint.d
    depends_on:
      - moodle-db

  moodle-cron:
    image: moodlehq/moodle-php-apache:8.3
    container_name: moodle-cron
    restart: unless-stopped
    environment:
      # Fixes zend.exception_ignore_args warning, removes sensitive information from logs in prod
      - PHP_INI-zend.exception_ignore_args=On
    volumes:
      - ./bind-mounts/html:/var/www/html
      - ./bind-mounts/moodledata:/var/www/moodledata
      - ./entrypoint-scripts:/docker-entrypoint.d
    depends_on:
      - moodle-db
    # Instead of running the Apache web server, this container runs the Moodle cron every minute in an infinite loop
    command: >
      sh -c "while true; do php /var/www/html/admin/cli/cron.php; sleep 60; done"