services:
  moodle:
    ports:
      - "8080:80"
    environment:
      # Revert security measure from prod in dev so logs include sensitive information for debugging
      - PHP_INI-zend.exception_ignore_args=Off
  moodle-cron:
    environment:
      # Revert security measure from prod in dev so logs include sensitive information for debugging
      - PHP_INI-zend.exception_ignore_args=Off