services:
  moodle:
    build:
      context: .
      dockerfile: moodle.Dockerfile
      target: moodle # Use the 'moodle' stage for local development to get better error messages and stack traces
    ports:
      - "8080:80"